### ISSUE TITLE
运行失败

### ISSUE THREAD

**Issue by hu975110710** [stay-leave/weibo-public-opinion-analysis#1]

**Comment by hu975110710** [comment]
运行不了，大佬可以说说要改些啥东西吗

**Comment by stay-leave** [comment]
麻烦说下是哪部分不清楚？

**Comment by hu975110710** [comment]
注：所有代码都需要修改源文件的路径和爬取到的数据文件的路径。
这个部分，不知道在哪里修改

**Comment by hu975110710** [comment]
爬虫中的comment crawler.py

**Comment by stay-leave** [comment]
save_afile()函数里的文件夹是要自建的，爬取到的微博的评论都在这个文件夹里。
主函数的文件是微博正文文件，用我提到的爬取微博正文的项目爬取就行。
基本上所有的文件夹都需要自己新建（我比较懒）。
最近我也在用，建议是每次用随机的cookie，不用多线程，防止反爬。

**Comment by hu975110710** [comment]
非常感谢！我研究一下！谢谢！

**Comment by hu975110710** [comment]
大佬，正文中的项目爬取微博项目weibo-search，我之前也有用过，挺好用，今天我用好像失效了，你试试还能用吗

**Comment by stay-leave** [comment]
可以用啊，刚用了的，就是爬取不了点赞数

**Comment by stay-leave** [comment]
可能是你cookie失效了

**Comment by hu975110710** [comment]
我关键词好像爬不了了，奇怪
