### ISSUE TITLE
关于困惑度

### ISSUE THREAD

**Issue by 2871858184** [stay-leave/weibo-public-opinion-analysis#16]
博主您好，在我用您的代码进行计算时，发现计算出来的困惑度为负数，但是我看很多论文里面计算结果都是正的，请问您知道这是为什么吗？

**Comment by stay-leave** [comment]
非常感谢你的提问，由于我在当时也不是很懂，没在意困惑度是负数了。
在lda.py的第100行我计算了困惑度，使用LdaModel类的log_perplexity()函数来计算LDA模型的困惑度，该函数返回的是模型的对数似然函数值的相反数。

所以，我们需要对该值取指数才能得到LDA模型的困惑度。
可以将其修改为perplexity = np.exp(-
Ida_model.log_perplexity(corpus))，这样就转为正数了。

Ida_model.log_perplexity(test_corpu
s）计算得到对数似然函数值的相反数，
即LDA模型的困惑度，‘np.exp(）函数将
困惑度的值转换为正数。

np就是numpy

**Comment by 2871858184** [comment]
谢谢您的回答！
