### ISSUE TITLE
主题重要性区分

### ISSUE THREAD

**Issue by 2871858184** [stay-leave/weibo-public-opinion-analysis#17]
请问楼主为什么可视化之后左边的圆圈会一样大呢？即每个主题都一样重要。

**Comment by 2871858184** [comment]
我在计算过程中发现有些主题的文本数量存在差异，可是并没有在可视化中体现出来。

**Comment by stay-leave** [comment]
可视化代码在lda.py的107行，我直接用了pyLDAvis.gensim.prepare，我发现我之前做的也是一样大。你可以查下还有别的更好的可视化方法可以处理这一问题吗。

**Comment by 2871858184** [comment]
您每一个主题的文本数量很相近吗

**Comment by 2871858184** [comment]
我在想除了可视化这里，别的地方会不会也存在问题

**Comment by stay-leave** [comment]
可以检查下lda文件，找找里面有哪些问题，我最近没时间

**Comment by Lan-ce-lot** [comment]
我查看了每个圆的CSS
<img width="213" alt="image" src="https://user-images.githubusercontent.com/53330071/221761069-e621ce59-3c6f-44a5-9535-4f20c8894623.png">
<img width="212" alt="image" src="https://user-images.githubusercontent.com/53330071/221761241-d5d04448-c77d-4743-967b-c13f10c65416.png">
他们的大小是不一样的，只是r差距太小，看起来一样。。。

**Comment by Lan-ce-lot** [comment]
> 请问楼主为什么可视化之后左边的圆圈会一样大呢？即每个主题都一样重要。

你可以看看是不是这样🦄

**Comment by stay-leave** [comment]
![image](https://user-images.githubusercontent.com/58450966/222034642-790facee-9633-4146-a0ab-da09c4b41669.png)
确实是这样
