### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by Zhouzhoumiao1** [stay-leave/weibo-public-opinion-analysis#3]
作者你好，请问你的爬虫获取下来的数据里有没有一些你不需要的数据，（例如：一些打广告的），这些数据你是清洗掉了吗？有一些很难清洗的数据，你是怎么清洗的呢？方便给我的邮箱回复一个你的联系方式吗？wangyi9262021@163.com   非常感谢！

**Comment by stay-leave** [comment]
我是使用爬虫目录下的data cleaning文件来清洗的，方法有自建词表、正则还有第三方库这些，在我关注的新冠疫苗领域基本上是清洗掉了。

**Comment by Zhouzhoumiao1** [comment]
> 

你好，请问你这个项目的爬取的数据还有吗？你的代码里有些地方我没看明白，想通过你的数据跑一下看看是怎么回事，方便发一份吗？
