### ISSUE TITLE
正文_2.xlsx

### ISSUE THREAD

**Issue by 123zcy** [stay-leave/weibo-public-opinion-analysis#5]

**Comment by 123zcy** [comment]
您好，能否分享一下正文_2.xlsx的格式 和数据？谢谢您

**Comment by stay-leave** [comment]
具体在哪段代码里？麻烦截图看看

**Comment by 123zcy** [comment]
> 具体在哪段代码里？麻烦截图看看

![image](https://user-images.githubusercontent.com/39721645/157596254-26a552f8-9d5d-46e3-95e0-80fc201d32e0.png)

**Comment by stay-leave** [comment]
![image](https://user-images.githubusercontent.com/58450966/157604433-308f6baa-8fb2-4105-a99e-a3b8466551ae.png)
最新的评论是你吗？我已经给这个邮箱发了

**Comment by Dear-keke** [comment]
楼主你好 请问这个是整个系统 还是要在Jupyter Notebook中一步一步的进行

**Comment by stay-leave** [comment]
是要一步步运行的，先爬取微博正文，然后是评论及用户信息的爬取，之后对微博正文进行主题抽取（后续就是主题相似度、热度），对评论计算情感值（联系用户信息进行空间分析）。具体见每个文件夹的说明文件

**Comment by 123zcy** [comment]
是我，谢谢！
