### ISSUE TITLE
爬取用户信息失败

### ISSUE THREAD

**Issue by jiayin0509** [stay-leave/weibo-public-opinion-analysis#6]
您好，在爬取用户信息时显示正常爬取中，也创建了这个表，但是表却是空表，请问这是什么情况呢？

**Comment by stay-leave** [comment]
请访问下你的目标网址看一下。也没有任何报错吗

**Comment by jiayin0509** [comment]
没有报错，也能打开

**Comment by jiayin0509** [comment]
不过单个资料爬取时候进行打印基本信息时数据为空

**Comment by stay-leave** [comment]
![image](https://user-images.githubusercontent.com/58450966/158343037-eb859add-240b-49f3-b2b2-3212bf1737d2.png)
抱歉，我忘了我在save_afile()函数下每次都新建了个sheet。在那里面

**Comment by jiayin0509** [comment]
也怪我，没注意到这些。。不过爬取后除了UID之外其他的还是空白

**Comment by stay-leave** [comment]
你用随机cookie版本试试

**Comment by stay-leave** [comment]
你用随机cookie版本的，同时多添加几个cookie，我刚试了，没问题

**Comment by jiayin0509** [comment]
好的 我试试，辛苦啦哈  先谢谢哈

**Comment by summer-mood** [comment]
请问一下，原本网页的评论有很多条，但是用随机cookie版本爬取评论信息为什么只能爬取到很少几条信息呢，是cookie的问题吗，这里的cookie应该是什么呢，还是说有其他方面需要注意的？
![image](https://user-images.githubusercontent.com/34939163/158388952-adf7c834-4bd9-4111-a33e-d0efe3062171.png)
![image](https://user-images.githubusercontent.com/34939163/158389411-e318c9b0-63ae-43b3-83c7-bbacef428a3f.png)

**Comment by stay-leave** [comment]
![image](https://user-images.githubusercontent.com/58450966/158394875-f8dad9d9-1b76-40e7-845f-57f11d5e20f9.png)
cookie在这里面，是微博账号的登录缓存信息。感觉你的不对。
其次若太少可以把等待时间延长，例如最后的t.sleep()里面改成1——9的数字，越大等待越久。
我今天又跑了一次，没问题。若还有问题可以cdsn私信我。

**Comment by summer-mood** [comment]
csdn如何私信你呢

**Comment by stay-leave** [comment]
搜 灵海之森

**Comment by ligongzi0** [comment]
作者你好，出现“PermissionError”这个错误是怎么回事啊？显示已经保存了的数据也没有被保存。

**Comment by stay-leave** [comment]
可能是你的电脑没有给Python程序访问文件系统的权限？我没见过这个，你百度下看看。

**Comment by ligongzi0** [comment]
> 可能是你的电脑没有给Python程序访问文件系统的权限？我没见过这个，你百度下看看。

好的，谢谢了！
