### ISSUE TITLE
正文_2.xlsx

### ISSUE THREAD

**Issue by summer-mood** [stay-leave/weibo-public-opinion-analysis#7]
![image](https://user-images.githubusercontent.com/34939163/158345265-14df87f4-c612-4567-8910-100acbdfb20a.png)
你好，这个“正文_2.xlsx”可以发一下吗

**Comment by stay-leave** [comment]
![image](https://user-images.githubusercontent.com/58450966/158352708-471ee60e-ff8e-4fbc-9dbc-e2245aeac5ef.png)
这个就是使用我说的那个大神的程序爬取下来的数据。看说明文档

**Comment by summer-mood** [comment]
明白了，谢谢大神
